"""
services/explanation_service.py — Gemini AI explanation generator.

SRP  : builds prompts and calls the API — nothing else.
ISP  : private methods for prompt building keep the public interface minimal.
DIP  : the genai model is injected, never instantiated internally.
"""
import google.generativeai as genai


class ExplanationService:
    """
    Generates structured medical explanations for brain-tumour saliency maps
    using a two-turn Gemini chat session.

    Parameters
    ----------
    genai_model : genai.GenerativeModel
        An already-configured GenerativeModel instance (injected by app.py).
    """

    def __init__(self, genai_model: genai.GenerativeModel) -> None:
        self._model = genai_model

    # ── Public API ─────────────────────────────────────────────────────────

    def explain(self, img_path: str, prediction: str, confidence: float) -> str:
        """
        Run a two-turn Gemini chat to produce a refined medical report.

        Parameters
        ----------
        img_path   : str   Path to the saliency-map image (used as context label).
        prediction : str   Predicted class label (e.g. "Glioma").
        confidence : float Model confidence in [0, 1].

        Returns
        -------
        str
            The refined explanation, or an error message string.
        """
        try:
            initial_prompt = self._build_initial_prompt(prediction, confidence)
            chat = self._model.start_chat(
                history=[{"role": "user", "parts": [initial_prompt]}]
            )
            initial_response = chat.send_message("Begin explanation.").text
            if not initial_response:
                return "No response received from the Generative AI model."

            refinement_prompt = self._build_refinement_prompt(initial_response)
            refined_response = chat.send_message(refinement_prompt).text
            if not refined_response:
                return "No refined response received from the Generative AI model."

            return refined_response

        except Exception as exc:
            return f"Error generating explanation: {exc}"

    # ── Private helpers ────────────────────────────────────────────────────

    def _build_initial_prompt(self, prediction: str, confidence: float) -> str:
        return f"""You are an expert neurologist. You are tasked with explaining a saliency map \
of a brain tumor MRI scan. The saliency map was generated by a deep learning model that was \
trained to classify brain tumors as either glioma, meningioma, pituitary, or no tumor.

The saliency map highlights the regions of the image that the machine learning model is focusing \
on to make the prediction.

The deep learning model predicted the image to be of class '{prediction}' with a confidence of \
{confidence * 100:.2f}%.

In your final response:
- Explain what regions of the brain the model is focusing on, based on the saliency map. Refer \
to the regions highlighted in light cyan, those are the regions where the model is focusing on.
- Include all the numbers in this data, and what they represent.

Let's think step by step about this. Verify step by step.
"""

    def _build_refinement_prompt(self, initial_response: str) -> str:
        return f"""Based on the following expert analysis of the saliency map:

"{initial_response}"

Using this analysis, please provide a comprehensive report structured with the following sections:

- **Introduction**: Overview of the saliency map's purpose, model design and training context, \
and the importance of interpretability in ML-based medical diagnoses.

- **Data and Methods**: Briefly describe the model's architecture, any layers particularly \
relevant to the prediction, and how the saliency map was generated. Explain the significance of \
highlighted regions and their relation to tumour detection.

- **Results**: Interpret the model's findings based on highlighted regions. Explain which brain \
regions are emphasised, their relevance to the predicted tumour type, and how they contribute to \
the model's confidence.

- **Conclusion**: Summarise the saliency map's insights, the model's confidence, and diagnostic \
value for clinicians.

- **Recommendations**: Evidence-based next steps — additional diagnostics, consultations, or \
treatment options. Conclude with model limitations relevant to clinical decisions.

Aim for no more than 8 sentences total. Structure the report for review by medical professionals \
and data scientists, balancing interpretability with technical precision.

Think through each part step by step and verify each step for clarity, accuracy, and relevance.
"""
